idrac:
  hosts:
    test001:
      ansible_connection: local
      ansible_host:       192.168.11.238
      ansible_user:       ansible 
amt:
  hosts:
    test002:
      ansible_connection: local
      ansible_host:       192.168.1.171
      ansible_user:       ansible 
