# Example ansible YAML file

- hosts: idracs
  vars:
    serial_enable:      "1"
    idrac_username:     "root"
    idrac_password:     "calvin"
    execute_get:        "yes"
    execute_set:        "no"
    idrac_sshkey_file:  "/home/user/.ssh/id_rsa"

  connection: local
  become: True

  tasks:
    - include: python/modules.yaml
#    - include: idrac/rac_get_new.yaml
#    - include: idrac/rac_get_old.yaml
#    - include: idrac/rac_set_new.yaml
#    - include: idrac/rac_set_old.yaml
#    - include: idrac/ssh_get_new.yaml
    - include: idrac/ssh_get_new_ssh_key.yaml
#    - include: idrac/ssh_get_old.yaml
#    - include: idrac/ssh_get_old_ssh_key.yaml
#    - include: idrac/ssh_set_new.yaml
#    - include: idrac/ssh_set_new_ssh_key.yaml
#    - include: idrac/ssh_set_old.yaml
#    - include: idrac/ssh_set_old_ssh_key.yaml
